/**
 * Metadata Factory
 * Centralized metadata generation for consistent SEO across 100K+ pages
 * Prevents duplication, keyword cannibalization, and thin content
 */

import type { Metadata } from "next";
import { SEO_CONFIG, BASE_URL, type PageType } from "./constants";

/**
 * Base configuration for metadata generation
 */
export interface MetadataConfig {
  /** Page type for determining template and schema */
  type: PageType;
  /** Primary title - will be templated based on page type */
  title: string;
  /** Meta description - should be unique and 150-160 chars */
  description: string;
  /** URL path (without base URL) */
  path: string;
  /** Additional keywords for the page */
  keywords?: string[];
  /** Whether to noindex this page */
  noIndex?: boolean;
  /** Published date (ISO string) */
  publishedTime?: string;
  /** Modified date (ISO string) */
  modifiedTime?: string;
  /** Custom OG image configuration */
  image?: {
    url: string;
    alt: string;
    width?: number;
    height?: number;
  };
  /** Author information */
  author?: string;
  /** Section/category the content belongs to */
  section?: string;
}

/**
 * Title templates by page type to avoid cannibalization
 * Each template creates unique, intent-matched titles
 */
const TITLE_TEMPLATES: Record<PageType, (title: string) => string> = {
  home: () => "Sub-Agents Directory - Claude Code Prompts & MCP Servers",
  rule: (title) => `${title} - Claude Code Sub-Agent Prompt`,
  category: (title) => `${title} Claude Code Sub-Agents`,
  mcp: (title) => `${title} MCP Server for Claude Code`,
  "mcp-category": (title) => `${title} MCP Servers`,
  tool: (title) => `Claude Code Agents Using ${title}`,
  framework: (title) => `Claude Code Agents for ${title}`,
  comparison: (title) => title, // Already formatted as "X vs Y"
  "use-case": (title) => title, // Already formatted
  tutorial: (title) => `${title} - Claude Code Tutorial`,
  guide: (title) => `${title} - Claude Code Guide`,
  "user-profile": (title) => `${title}'s Claude Code Prompts`,
  generation: (title) => `${title} - Custom Claude Code Prompt`,
  learn: () => "Learn Claude Code - Tutorials & Guides",
  about: () => "About Sub-Agents Directory",
  generic: (title) => title,
};

/**
 * Description templates by page type for unique descriptions
 */
const DESCRIPTION_TEMPLATES: Record<PageType, (desc: string, title: string) => string> = {
  home: () => SEO_CONFIG.defaultDescription,
  rule: (desc, title) =>
    desc ||
    `Get the ${title} sub-agent prompt for Claude Code. Copy-paste ready with expert instructions.`,
  category: (desc) => desc,
  mcp: (desc, title) =>
    desc ||
    `${title} MCP server integration for Claude Code. Connect and extend Claude's capabilities.`,
  "mcp-category": (desc) => desc,
  tool: (desc, title) =>
    desc ||
    `Browse Claude Code sub-agents that use ${title}. Find the right prompt for your project.`,
  framework: (desc, title) =>
    desc ||
    `Claude Code sub-agents specialized in ${title}. Expert prompts for ${title} development.`,
  comparison: (desc) => desc,
  "use-case": (desc) => desc,
  tutorial: (desc) => desc,
  guide: (desc) => desc,
  "user-profile": (desc, title) => desc || `Browse custom Claude Code prompts created by ${title}.`,
  generation: (desc) => desc || "Custom Claude Code sub-agent prompt generated by the community.",
  learn: () => "Learn how to use Claude Code with tutorials, guides, and video content.",
  about: () =>
    "Learn about Sub-Agents Directory, the largest collection of Claude Code prompts and MCP servers.",
  generic: (desc) => desc,
};

/**
 * Generate full canonical URL
 */
export function getCanonicalUrl(path: string): string {
  const cleanPath = path.startsWith("/") ? path : `/${path}`;
  return `${BASE_URL}${cleanPath}`;
}

/**
 * Generate OG image URL with dynamic parameters
 */
export function getOgImageUrl(path: string, _config?: { title?: string; type?: PageType }): string {
  // For dynamic OG images, use the path-based route
  if (path === "/" || path === "") {
    return `${BASE_URL}/cover-image.png`;
  }
  // For pages with dynamic OG images
  return `${BASE_URL}${path}/opengraph-image`;
}

/**
 * Create complete metadata object for any page type
 */
export function createMetadata(config: MetadataConfig): Metadata {
  const {
    type,
    title,
    description,
    path,
    keywords = [],
    noIndex = false,
    publishedTime,
    modifiedTime,
    image,
    author = SEO_CONFIG.siteName,
    section,
  } = config;

  const processedTitle = TITLE_TEMPLATES[type](title);
  const processedDescription = DESCRIPTION_TEMPLATES[type](description, title);
  const canonicalUrl = getCanonicalUrl(path);
  const ogImageUrl = image?.url || getOgImageUrl(path, { title, type });

  // Base keywords always included
  const baseKeywords = ["Claude Code", "sub-agents", "AI prompts", "Anthropic"];
  const allKeywords = [...new Set([...baseKeywords, ...keywords])];

  const metadata: Metadata = {
    title: processedTitle,
    description: processedDescription,
    keywords: allKeywords,
    authors: [{ name: author }],
    creator: SEO_CONFIG.siteName,
    publisher: SEO_CONFIG.siteName,
    alternates: {
      canonical: canonicalUrl,
    },
    robots: noIndex
      ? { index: false, follow: true }
      : {
          index: true,
          follow: true,
          googleBot: {
            index: true,
            follow: true,
            "max-video-preview": -1,
            "max-image-preview": "large",
            "max-snippet": 160,
          },
        },
    openGraph: {
      title: processedTitle,
      description: processedDescription,
      url: canonicalUrl,
      siteName: SEO_CONFIG.siteName,
      locale: SEO_CONFIG.locale,
      type: getOgType(type),
      images: [
        {
          url: ogImageUrl,
          width: image?.width || 1200,
          height: image?.height || 630,
          alt: image?.alt || processedTitle,
        },
      ],
      ...(publishedTime && { publishedTime }),
      ...(modifiedTime && { modifiedTime }),
      ...(author && { authors: [author] }),
    },
    twitter: {
      card: "summary_large_image",
      title: processedTitle,
      description: processedDescription,
      images: [ogImageUrl],
    },
  };

  // Add article-specific metadata
  if (isArticleType(type) && section) {
    (metadata.openGraph as Record<string, unknown>).section = section;
  }

  return metadata;
}

/**
 * Determine OG type based on page type
 */
function getOgType(type: PageType): "website" | "article" | "profile" {
  const articleTypes: PageType[] = ["rule", "tutorial", "guide", "comparison", "generation"];
  const profileTypes: PageType[] = ["user-profile"];

  if (articleTypes.includes(type)) return "article";
  if (profileTypes.includes(type)) return "profile";
  return "website";
}

/**
 * Check if page type should have article metadata
 */
function isArticleType(type: PageType): boolean {
  return ["rule", "tutorial", "guide", "comparison", "generation"].includes(type);
}

/**
 * Generate metadata for rule pages
 */
export function createRuleMetadata(rule: {
  title: string;
  slug: string;
  description?: string;
  content?: string;
  tags?: string[];
  libs?: string[];
}): Metadata {
  const description = rule.description || cleanDescription(rule.content || "", 155);

  return createMetadata({
    type: "rule",
    title: rule.title,
    description,
    path: `/${rule.slug}`,
    keywords: [...(rule.tags || []), ...(rule.libs || [])],
    section: rule.tags?.[0],
    publishedTime: "2024-01-01T00:00:00Z",
    modifiedTime: new Date().toISOString(),
  });
}

/**
 * Generate metadata for category pages
 */
export function createCategoryMetadata(category: {
  name: string;
  slug: string;
  description: string;
  keywords?: string[];
  count: number;
}): Metadata {
  return createMetadata({
    type: "category",
    title: category.name,
    description: category.description,
    path: `/agents/${category.slug}`,
    keywords: category.keywords || [],
  });
}

/**
 * Generate metadata for MCP pages
 */
export function createMcpMetadata(mcp: {
  name: string;
  slug: string;
  description: string;
}): Metadata {
  return createMetadata({
    type: "mcp",
    title: mcp.name,
    description: mcp.description,
    path: `/mcp/${mcp.slug}`,
    keywords: ["MCP server", mcp.name, "Claude Code integration"],
  });
}

/**
 * Generate metadata for comparison pages
 */
export function createComparisonMetadata(comparison: {
  rule1: { title: string; slug: string };
  rule2: { title: string; slug: string };
  description?: string;
}): Metadata {
  const title = `${comparison.rule1.title} vs ${comparison.rule2.title}: Which Claude Code Agent to Use?`;
  const description =
    comparison.description ||
    `Compare ${comparison.rule1.title} and ${comparison.rule2.title} Claude Code sub-agents. Find out which is best for your project.`;

  return createMetadata({
    type: "comparison",
    title,
    description,
    path: `/agents/compare/${comparison.rule1.slug}-vs-${comparison.rule2.slug}`,
    keywords: [comparison.rule1.title, comparison.rule2.title, "comparison"],
  });
}

/**
 * Generate metadata for use case pages
 */
export function createUseCaseMetadata(useCase: {
  name: string;
  slug: string;
  title: string;
  description: string;
  keywords?: string[];
}): Metadata {
  return createMetadata({
    type: "use-case",
    title: useCase.title,
    description: useCase.description,
    path: `/agents/for/${useCase.slug}`,
    keywords: useCase.keywords || [],
  });
}

/**
 * Generate metadata for tool pages
 */
export function createToolMetadata(tool: {
  name: string;
  slug: string;
  description?: string;
  count: number;
}): Metadata {
  const description =
    tool.description ||
    `Discover ${tool.count} Claude Code sub-agents that use ${tool.name}. Find the right prompt for your ${tool.name} project.`;

  return createMetadata({
    type: "tool",
    title: tool.name,
    description,
    path: `/agents/tools/${tool.slug}`,
    keywords: [tool.name, "Claude Code tools"],
  });
}

/**
 * Generate metadata for user profile pages
 */
export function createUserProfileMetadata(user: {
  username: string;
  displayName?: string;
  bio?: string;
  generationCount?: number;
}): Metadata {
  const name = user.displayName || user.username;
  const description =
    user.bio ||
    `View Claude Code prompts created by ${name}. ${user.generationCount || 0} custom prompts.`;

  return createMetadata({
    type: "user-profile",
    title: name,
    description,
    path: `/u/${user.username}`,
    noIndex: (user.generationCount || 0) < 3, // Don't index profiles with few generations
  });
}

/**
 * Generate metadata for generation pages
 */
export function createGenerationMetadata(generation: {
  title: string;
  slug: string;
  description?: string;
  content?: string;
  authorName?: string;
}): Metadata {
  const description =
    generation.description ||
    cleanDescription(generation.content || "", 155) ||
    "Custom Claude Code sub-agent prompt generated by the community.";

  return createMetadata({
    type: "generation",
    title: generation.title,
    description,
    path: `/g/${generation.slug}`,
    author: generation.authorName,
    noIndex: !generation.description && !generation.content, // Don't index empty generations
  });
}

/**
 * Clean description text for meta tags
 */
function cleanDescription(content: string, maxLength = 155): string {
  return content
    .replace(/```[\s\S]*?```/g, "")
    .replace(/`[^`]+`/g, "")
    .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
    .replace(/[#*_~>-]/g, "")
    .replace(/\n+/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, maxLength);
}
